update to support template

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -12,38 +12,85 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-      - name: Setup Godot
+      - name: Setup Godot (editor only)
         uses: ./
         with:
           version: '4.4.1-stable'
-          platform: 'linux.x86_64'
       - name: Check Godot version
         run: |
           $GODOT4 --version
+      - name: Setup Godot (editor + templates)
+        uses: ./
+        with:
+          version: '4.4.1-stable'
+          download_template: 'true'
+      - name: Check templates
+        run: |
+          ls godot-bin/templates || echo "No templates found"
+      - name: Setup Godot (mono)
+        uses: ./
+        with:
+          version: '4.4.1-stable'
+          mono: 'true'
+      - name: Check Godot mono version
+        run: |
+          $GODOT4 --version || echo "Mono binary not found"
   test-godot-setup-macos:
     runs-on: macos-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-      - name: Setup Godot
+      - name: Setup Godot (editor only)
         uses: ./
         with:
           version: '4.4.1-stable'
-          platform: 'macos.universal'
       - name: Check Godot version
         run: |
           $GODOT4 --version
+      - name: Setup Godot (editor + templates)
+        uses: ./
+        with:
+          version: '4.4.1-stable'
+          download_template: 'true'
+      - name: Check templates
+        run: |
+          ls godot-bin/templates || echo "No templates found"
+      - name: Setup Godot (mono)
+        uses: ./
+        with:
+          version: '4.4.1-stable'
+          mono: 'true'
+      - name: Check Godot mono version
+        run: |
+          $GODOT4 --version || echo "Mono binary not found"
   test-godot-setup-windows:
     runs-on: windows-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-      - name: Setup Godot
+      - name: Setup Godot (editor only)
         uses: ./
         with:
           version: '4.4.1-stable'
-          platform: 'win64.exe'
       - name: Check Godot version
         shell: pwsh
         run: |
           & $env:GODOT4 --version
+      - name: Setup Godot (editor + templates)
+        uses: ./
+        with:
+          version: '4.4.1-stable'
+          download_template: 'true'
+      - name: Check templates
+        shell: pwsh
+        run: |
+          Get-ChildItem godot-bin/templates -ErrorAction SilentlyContinue
+      - name: Setup Godot (mono)
+        uses: ./
+        with:
+          version: '4.4.1-stable'
+          mono: 'true'
+      - name: Check Godot mono version
+        shell: pwsh
+        run: |
+          & $env:GODOT4 --version || Write-Host "Mono binary not found"
